name: "dog_breeds"
version: "1.0.0"
config-version: 2
profile: "dog_breeds"

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dog_breeds:
    staging:
      +materialized: view
    marts:
      +materialized: table
